version: '2'
services:

  mysql:
    image: docker.io/bitnami/mysql:8.0
    networks:
      - wordpress-network
    volumes:
      - 'mysql_data:/bitnami/mysql'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=bn_wordpress
      - MYSQL_DATABASE=bitnami_wordpress

  wordpress:
    image: docker.io/bitnami/wordpress:6
    networks:
      - wordpress-network
    volumes:
      - './wordpress:/bitnami/wordpress'
    depends_on:
      - mysql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mysql
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress

  redis:
    image: docker.io/bitnami/redis
    networks:
      - wordpress-network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "redis_data:/bitnami/redis/data"

  nginx:
    image: nginx:latest
    networks:
      - wordpress-network
    depends_on:
      - wordpress
    links:
      - wordpress
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx/core.conf:/etc/nginx/conf.d/core.conf'
      - './nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf'
      - './nginx/wordpress.conf:/etc/nginx/conf.d/wordpress.conf'

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
    wordpress-network:
        driver: bridge