
version: '2'
services:

  mysql:
    image: docker.io/bitnami/mysql
    networks:
      - wordpress-network
    volumes:
      - 'mysql_data:/bitnami/mysql'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=bn_wordpress
      - MYSQL_DATABASE=bitnami_wordpress

  redis:
    image: docker.io/bitnami/redis
    networks:
      - wordpress-network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "redis_data:/bitnami/redis/data"

  wordpress:
    image: docker.io/bitnami/wordpress-nginx:6
    networks:
      - wordpress-network
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mysql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mysql
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  wordpress-network:
    driver: bridge